const { CATEGORIES, categoryOf, nameOf } = require('../config/coinCategories')

const BINANCE_EXCHANGE_INFO_URL = 'https://api.binance.com/api/v3/exchangeInfo'
const BINANCE_TICKER_24H_URL = 'https://api.binance.com/api/v3/ticker/24hr'
const CACHE_TTL_MS = 6 * 60 * 60 * 1000 // 6h - the list of tradable pairs doesn't change often
const VOLUME_CACHE_TTL_MS = 15 * 60 * 1000 // 15min - le volume bouge vite, contrairement à la liste des paires

const JUNK_SYMBOL_REGEX = /^\d/

function isJunkSymbol(symbol) {
  return JUNK_SYMBOL_REGEX.test(symbol) || symbol.length < 3
}

let _cache = { symbols: null, fetchedAt: 0 }
let _volumeCache = { volumes: null, fetchedAt: 0 }

// { symbol: "BTCUSDT", base: "BTC", quote: "USDT" }[] - only the pairs
// currently tradable (status TRADING) on Binance.
async function getTradingSymbols() {
  if (_cache.symbols && Date.now() - _cache.fetchedAt < CACHE_TTL_MS) return _cache.symbols

  try {
    const res = await fetch(BINANCE_EXCHANGE_INFO_URL)
    if (!res.ok) throw new Error(`Binance API ${res.status}`)
    const json = await res.json()
    const symbols = json.symbols
      .filter(s => s.status === 'TRADING')
      .map(s => ({ symbol: s.symbol, base: s.baseAsset, quote: s.quoteAsset }))
    _cache = { symbols, fetchedAt: Date.now() }
    return symbols
  } catch (e) {
    console.error('[coinService] Binance exchangeInfo fetch failed:', e.message)
    // If we have a cache, even a stale one, better to serve it than break the page.
    if (_cache.symbols) return _cache.symbols
    throw new Error('COIN_LIST_UNAVAILABLE')
  }
}

async function getTicker24hVolumes() {
  if (_volumeCache.volumes && Date.now() - _volumeCache.fetchedAt < VOLUME_CACHE_TTL_MS) {
    return _volumeCache.volumes
  }

  try {
    const res = await fetch(BINANCE_TICKER_24H_URL)
    if (!res.ok) throw new Error(`Binance API ${res.status}`)
    const json = await res.json()
    const volumes = new Map(json.map(t => [t.symbol, parseFloat(t.quoteVolume) || 0]))
    _volumeCache = { volumes, fetchedAt: Date.now() }
    return volumes
  } catch (e) {
    console.error('[coinService] Binance ticker/24hr fetch failed:', e.message)
    return _volumeCache.volumes || new Map()
  }
}

function assetVolume(symbol, volumes) {
  return volumes.get(`${symbol}USDT`) ?? volumes.get(`${symbol}USDC`) ?? 0
}

// Unique coins (base AND quote sides combined) available on Binance,
// enriched with their known name/category (coinCategories.js). A coin not
// listed in coinCategories.js still appears, just without a name or
// category (category: null -> "Uncategorized" on the sweep-results side).
// symbol ("BTCUSDT") -> quoteVolume (volume 24h dans la devise de quote)
async function listCoins() {
  const [symbols, volumes] = await Promise.all([getTradingSymbols(), getTicker24hVolumes()])
  const assets = new Set()
  symbols.forEach(s => { assets.add(s.base); assets.add(s.quote) })

  return [...assets]
    .filter(symbol => !isJunkSymbol(symbol))
    .map(symbol => ({
      symbol,
      name: nameOf(symbol),
      category: categoryOf(symbol),
      volume: assetVolume(symbol, volumes),
    }))
    .sort((a, b) => b.volume - a.volume)
    .map(({ symbol, name, category }) => ({ symbol, name, category })) // volume = tri interne seulement, pas exposé au front
}

async function listCategories() {
  return CATEGORIES
}

// Filters a set of candidate "BASE/QUOTE" pairs (e.g. generated by the
// base×quote cartesian product on the front end) to keep only the ones that
// actually exist on Binance.
async function filterValidPairs(pairs) {
  const symbols = await getTradingSymbols()
  const validSet = new Set(symbols.map(s => s.symbol))
  return pairs.filter(p => validSet.has(p.replace('/', '')))
}

module.exports = { getTradingSymbols, listCoins, listCategories, filterValidPairs, getTicker24hVolumes }