/**
 * Fixed registry of coin categories - edit manually to add
 * a known coin to a category (like INDICATOR_CATEGORIES on the front end,
 * public/js/indicator-picker.js). This is NOT a user-facing CRUD.
 *
 * The list of coins ACTUALLY available (i.e. shown in the picker and
 * offered for sweeps) comes live from the Binance API (see coinService.js),
 * not from this file. This file only categorizes and names known
 * coins; any coin listed by Binance but missing here simply falls
 * into "Uncategorized" (already handled by sweepService.getSweepGroup).
 *
 * category: one of the keys of CATEGORIES below.
 */

// NEW
const CATEGORIES = [
  { key: 'layer1',      label: 'Layer 1' },
  { key: 'layer2',      label: 'Layer 2' },
  { key: 'defi',        label: 'DeFi' },
  { key: 'meme',        label: 'Meme' },
  { key: 'stablecoin',  label: 'Stablecoin' },
  { key: 'exchange',    label: 'Exchange Token' },
  { key: 'ai',          label: 'AI' },
  { key: 'gaming',      label: 'Gaming / Metaverse' },
  { key: 'infra',       label: 'Infrastructure / Oracle' },
  { key: 'rwa',         label: 'RWA' },
  { key: 'privacy',     label: 'Privacy' },
  { key: 'stocks',      label: 'xStocks & ETFs' },
  { key: 'fantoken',    label: 'Sports Fan Token' },
  { key: 'fiat',        label: 'Fiat Currency' },
]

// symbol -> { name, category }
const COINS = {
  // Layer 1
  BTC:    { name: 'Bitcoin',        category: 'layer1' },
  ETH:    { name: 'Ethereum',       category: 'layer1' },
  SOL:    { name: 'Solana',         category: 'layer1' },
  AVAX:   { name: 'Avalanche',      category: 'layer1' },
  ADA:    { name: 'Cardano',        category: 'layer1' },
  DOT:    { name: 'Polkadot',       category: 'layer1' },
  NEAR:   { name: 'NEAR Protocol',  category: 'layer1' },
  APT:    { name: 'Aptos',          category: 'layer1' },
  SUI:    { name: 'Sui',            category: 'layer1' },
  TON:    { name: 'Toncoin',        category: 'layer1' },
  ATOM:   { name: 'Cosmos',         category: 'layer1' },
  ALGO:   { name: 'Algorand',       category: 'layer1' },
  XRP:    { name: 'XRP',            category: 'layer1' }, // native XRP Ledger asset, base chain, not just an infra token
  LTC:    { name: 'Litecoin',       category: 'layer1' },
  BCH:    { name: 'Bitcoin Cash',   category: 'layer1' },
  TRX:    { name: 'TRON',           category: 'layer1' },
  ETC:    { name: 'Ethereum Classic', category: 'layer1' },
  ICP:    { name: 'Internet Computer', category: 'layer1' },
  HBAR:   { name: 'Hedera',         category: 'layer1' },
  XPL:    { name: 'Plasma',         category: 'layer1' },
  SEI:    { name: 'Sei',            category: 'layer1' },
  EGLD:   { name: 'MultiversX',     category: 'layer1' },
  XTZ:    { name: 'Tezos',          category: 'layer1' },
  ONT:    { name: 'Ontology',       category: 'layer1' },
  GAS:    { name: 'NEO Gas',        category: 'layer1' },
  NEO:    { name: 'NEO',            category: 'layer1' },
  ONE:    { name: 'Harmony',        category: 'layer1' },
  QTUM:   { name: 'Qtum',           category: 'layer1' },
  ZIL:    { name: 'Zilliqa',        category: 'layer1' },
  IOTA:   { name: 'IOTA',           category: 'layer1' },
  IOTX:   { name: 'IoTeX',          category: 'layer1' },
  IOST:   { name: 'IOST',           category: 'layer1' },
  VET:    { name: 'VeChain',        category: 'layer1' },
  VTHO:   { name: 'VeThor',         category: 'layer1' }, // VET's companion gas token
  NEO_GAS:{ name: 'unused', category: 'layer1' }, // placeholder removed below
  CFX:    { name: 'Conflux',        category: 'layer1' },
  KSM:    { name: 'Kusama',         category: 'layer1' },
  CKB:    { name: 'Nervos Network', category: 'layer1' },
  ICX:    { name: 'ICON',           category: 'layer1' },
  QKC:    { name: 'QuarkChain',     category: 'layer1' },
  RVN:    { name: 'Ravencoin',      category: 'layer1' },
  DGB:    { name: 'DigiByte',       category: 'layer1' },
  XEC:    { name: 'eCash',          category: 'layer1' },
  DCR:    { name: 'Decred',         category: 'layer1' },
  LSK:    { name: 'Lisk',           category: 'layer1' },
  STRAX:  { name: 'Stratis',        category: 'layer1' },
  XNO:    { name: 'Nano',           category: 'layer1' },
  BTTC:   { name: 'BitTorrent Chain', category: 'layer1' },
  CELO:   { name: 'Celo',           category: 'layer1' },
  KAIA:   { name: 'Kaia',           category: 'layer1' },
  FOGO:   { name: 'Fogo',           category: 'layer1' },
  BERA:   { name: 'Berachain',      category: 'layer1' },
  MINA:   { name: 'Mina Protocol',  category: 'layer1' },
  CHR:    { name: 'Chromia',        category: 'layer1' },
  LUNA:   { name: 'Terra',          category: 'layer1' },
  LUNC:   { name: 'Terra Classic',  category: 'layer1' },
  INJ:    { name: 'Injective',      category: 'layer1' },

  // Layer 2 / rollups / appchains
  ARB:    { name: 'Arbitrum',       category: 'layer2' },
  OP:     { name: 'Optimism',       category: 'layer2' },
  MATIC:  { name: 'Polygon',        category: 'layer2' },
  POL:    { name: 'Polygon',        category: 'layer2' }, // POL supersedes MATIC as Polygon's native token
  STRK:   { name: 'Starknet',       category: 'layer2' },
  LINEA:  { name: 'Linea',          category: 'layer2' },
  SCR:    { name: 'Scroll',         category: 'layer2' },
  METIS:  { name: 'Metis',          category: 'layer2' },
  MANTA:  { name: 'Manta Network',  category: 'layer2' },
  MOVE:   { name: 'Movement',       category: 'layer2' },
  HEMI:   { name: 'Hemi',           category: 'layer2' },
  STX:    { name: 'Stacks',         category: 'layer2' },
  ASTR:   { name: 'Astar Network',  category: 'layer2' },
  GLMR:   { name: 'Moonbeam',       category: 'layer2' },
  MOVR:   { name: 'Moonriver',      category: 'layer2' },
  SOPH:   { name: 'Sophon',         category: 'layer2' },
  CTSI:   { name: 'Cartesi',        category: 'layer2' },
  SKL:    { name: 'SKALE',          category: 'layer2' },
  RIF:    { name: 'RSK Infrastructure Framework', category: 'layer2' },
  HYPER:  { name: 'Bitcoin Hyper',  category: 'layer2' }, // tentative: BTC L2, verify underlying project

  // DeFi
  UNI:    { name: 'Uniswap',        category: 'defi' },
  AAVE:   { name: 'Aave',           category: 'defi' },
  LDO:    { name: 'Lido DAO',       category: 'defi' },
  MKR:    { name: 'Maker',          category: 'defi' },
  CRV:    { name: 'Curve DAO',      category: 'defi' },
  COMP:   { name: 'Compound',       category: 'defi' },
  SUSHI:  { name: 'SushiSwap',      category: 'defi' },
  MORPHO: { name: 'Morpho',         category: 'defi' },
  PENDLE: { name: 'Pendle',         category: 'defi' },
  EUL:    { name: 'Euler',          category: 'defi' },
  CAKE:   { name: 'PancakeSwap',    category: 'defi' },
  SNX:    { name: 'Synthetix',      category: 'defi' },
  GNS:    { name: 'Gains Network',  category: 'defi' },
  GMX:    { name: 'GMX',            category: 'defi' },
  DYDX:   { name: 'dYdX',           category: 'defi' },
  JOE:    { name: 'Trader Joe',     category: 'defi' },
  CETUS:  { name: 'Cetus Protocol', category: 'defi' },
  VELODROME: { name: 'Velodrome',   category: 'defi' },
  AERO:   { name: 'Aerodrome',      category: 'defi' },
  QUICK:  { name: 'QuickSwap',      category: 'defi' },
  UMA:    { name: 'UMA',            category: 'defi' },
  KAVA:   { name: 'Kava',           category: 'defi' },
  RSR:    { name: 'Reserve Rights', category: 'defi' },
  SPELL:  { name: 'Abracadabra Money', category: 'defi' },
  YFI:    { name: 'Yearn Finance',  category: 'defi' },
  ZRX:    { name: '0x Protocol',    category: 'defi' },
  CVX:    { name: 'Convex Finance', category: 'defi' },
  LQTY:   { name: 'Liquity',        category: 'defi' },
  SKY:    { name: 'Sky',            category: 'defi' }, // formerly MakerDAO rebrand
  DODO:   { name: 'DODO',           category: 'defi' },
  ORCA:   { name: 'Orca',           category: 'defi' },
  RAY:    { name: 'Raydium',        category: 'defi' },
  JUP:    { name: 'Jupiter',        category: 'defi' },
  WOO:    { name: 'WOO Network',    category: 'defi' },
  BLUR:   { name: 'Blur',           category: 'defi' },
  STG:    { name: 'Stargate Finance', category: 'defi' },
  LISTA:  { name: 'Lista DAO',      category: 'defi' },
  HAEDAL: { name: 'Haedal',         category: 'defi' },
  SOLV:   { name: 'Solv Protocol',  category: 'defi' },
  ETHFI:  { name: 'Ether.fi',       category: 'defi' },
  REZ:    { name: 'Renzo Protocol', category: 'defi' },
  KERNEL: { name: 'Kernel DAO',     category: 'defi' },
  WBETH:  { name: 'Wrapped Beacon ETH', category: 'defi' },
  BNSOL:  { name: 'Binance Staked SOL', category: 'defi' },
  RPL:    { name: 'Rocket Pool',    category: 'defi' },
  JTO:    { name: 'Jito',           category: 'defi' },
  WLFI:   { name: 'World Liberty Financial', category: 'defi' },
  ENA:    { name: 'Ethena',         category: 'defi' },
  WBTC:   { name: 'Wrapped Bitcoin', category: 'defi' },
  MMT:    { name: 'Momentum',       category: 'defi' }, // tentative
  DEXE:   { name: 'DeXe Protocol',  category: 'defi' },
  KNC:    { name: 'Kyber Network Crystal', category: 'defi' },
  THE:    { name: 'THENA',          category: 'defi' },
  OGN:    { name: 'Origin Protocol', category: 'defi' },
  SHELL:  { name: 'Shell Protocol', category: 'defi' },
  DOLO:   { name: 'Dolomite',       category: 'defi' },
  C98:    { name: 'Coin98',         category: 'defi' },
  BEL:    { name: 'Bella Protocol', category: 'defi' },
  MAV:    { name: 'Maverick Protocol', category: 'defi' },
  AUCTION:{ name: 'Bounce Finance', category: 'defi' },
  LAYER:  { name: 'Solayer',        category: 'defi' },
  KMNO:   { name: 'Kamino Finance', category: 'defi' },
  AEVO:   { name: 'Aevo',           category: 'defi' },
  BNT:    { name: 'Bancor Network Token', category: 'defi' },
  RESOLV: { name: 'Resolv Protocol', category: 'defi' },
  BANANA: { name: 'ApeSwap',        category: 'defi' },
  XVS:    { name: 'Venus Protocol', category: 'defi' },
  ENSO:   { name: 'Enso Finance',   category: 'defi' },
  MITO:   { name: 'Mitosis',        category: 'defi' },
  COW:    { name: 'CoW Protocol',   category: 'defi' },
  SYRUP:  { name: 'Maple Finance',  category: 'defi' },
  SUN:    { name: 'SUN.io',         category: 'defi' },
  NEXO:   { name: 'Nexo',           category: 'defi' },
  JST:    { name: 'JUST',           category: 'defi' },
  OSMO:   { name: 'Osmosis',        category: 'defi' },
  BANK:   { name: 'Lorenzo Protocol', category: 'defi' }, // tentative
  AVNT:   { name: 'Avantis',        category: 'defi' }, // tentative

  // Meme
  DOGE:   { name: 'Dogecoin',       category: 'meme' },
  SHIB:   { name: 'Shiba Inu',      category: 'meme' },
  PEPE:   { name: 'Pepe',           category: 'meme' },
  WIF:    { name: 'dogwifhat',      category: 'meme' },
  FLOKI:  { name: 'Floki',          category: 'meme' },
  BONK:   { name: 'Bonk',           category: 'meme' },
  TRUMP:  { name: 'Official Trump', category: 'meme' },
  PNUT:   { name: 'Peanut the Squirrel', category: 'meme' },
  NEIRO:  { name: 'Neiro',          category: 'meme' },
  MEME:   { name: 'Memecoin',       category: 'meme' },
  TURBO:  { name: 'Turbo',          category: 'meme' },
  BOME:   { name: 'Book of Meme',   category: 'meme' },
  MUBARAK:{ name: 'Mubarak',        category: 'meme' },
  BROCCOLI714: { name: 'Broccoli',  category: 'meme' },
  BANANAS31: { name: 'Bananas31',   category: 'meme' },
  PENGU:  { name: 'Pudgy Penguins', category: 'meme' },
  ACT:    { name: 'Act I : The AI Prophecy', category: 'meme' },
  PUMP:   { name: 'Pump.fun',       category: 'meme' },
  ORDI:   { name: 'ORDI',           category: 'meme' }, // first BRC-20 token
  PEOPLE: { name: 'ConstitutionDAO', category: 'meme' },
  GIGGLE: { name: 'Giggle',         category: 'meme' }, // tentative

  // Stablecoin
  USDT:   { name: 'Tether',         category: 'stablecoin' },
  USDC:   { name: 'USD Coin',       category: 'stablecoin' },
  DAI:    { name: 'Dai',            category: 'stablecoin' },
  FDUSD:  { name: 'First Digital USD', category: 'stablecoin' },
  TUSD:   { name: 'TrueUSD',        category: 'stablecoin' },
  USD1:   { name: 'USD1',           category: 'stablecoin' },
  RLUSD:  { name: 'Ripple USD',     category: 'stablecoin' },
  XUSD:   { name: 'xUSD',           category: 'stablecoin' },
  EURI:   { name: 'EUR Stablecoin', category: 'stablecoin' },
  USDE:   { name: 'Ethena USDe',    category: 'stablecoin' },
  USDS:   { name: 'USDS',           category: 'stablecoin' }, // Sky/MakerDAO successor to DAI
  USDP:   { name: 'Pax Dollar',     category: 'stablecoin' },
  BFUSD:  { name: 'BFUSD',          category: 'stablecoin' },
  FRAX:   { name: 'Frax',           category: 'stablecoin' },
  USTC:   { name: 'TerraClassicUSD', category: 'stablecoin' }, // depegged, no longer $1 - kept for historical accuracy

  // Exchange Token
  BNB:    { name: 'BNB',            category: 'exchange' },
  OKB:    { name: 'OKB',            category: 'exchange' },
  CRO:    { name: 'Cronos',         category: 'exchange' },
  FTT:    { name: 'FTX Token',      category: 'exchange' }, // defunct exchange, token still trades
  TKO:    { name: 'Tokocrypto Token', category: 'exchange' },

  // AI
  FET:    { name: 'Artificial Superintelligence Alliance', category: 'ai' },
  RENDER: { name: 'Render',         category: 'ai' },
  WLD:    { name: 'Worldcoin',      category: 'ai' },
  TAO:    { name: 'Bittensor',      category: 'ai' },
  VIRTUAL:{ name: 'Virtuals Protocol', category: 'ai' },
  AIXBT:  { name: 'AIXBT',          category: 'ai' },
  ARKM:   { name: 'Arkham',         category: 'ai' },
  CGPT:   { name: 'ChainGPT',       category: 'ai' },
  KAITO:  { name: 'Kaito',          category: 'ai' },
  KITE:   { name: 'Kite',           category: 'ai' },
  OPEN:   { name: 'OpenLedger',     category: 'ai' },
  SXT:    { name: 'Space and Time', category: 'ai' },
  NMR:    { name: 'Numeraire',      category: 'ai' },
  VANA:   { name: 'Vana',           category: 'ai' },
  SAPIEN: { name: 'Sapien',         category: 'ai' }, // tentative
  MIRA:   { name: 'Mira Network',   category: 'ai' }, // tentative
  AIGENSYN: { name: 'Gensyn',       category: 'ai' }, // tentative
  SAHARA: { name: 'Sahara AI',      category: 'ai' }, // tentative
  HOLO:   { name: 'Holoworld AI',   category: 'ai' }, // tentative - not to confuse with Holochain (HOT)
  COOKIE: { name: 'Cookie DAO',     category: 'ai' }, // tentative
  ALLO:   { name: 'Allora Network', category: 'ai' }, // tentative
  SENT:   { name: 'Sentient',       category: 'ai' }, // tentative
  PROM:   { name: 'Prometeus',      category: 'ai' }, // tentative

  // Gaming / Metaverse
  SAND:   { name: 'The Sandbox',    category: 'gaming' },
  AXS:    { name: 'Axie Infinity',  category: 'gaming' },
  GALA:   { name: 'Gala',           category: 'gaming' },
  IMX:    { name: 'Immutable',      category: 'gaming' },
  ILV:    { name: 'Illuvium',       category: 'gaming' },
  MAGIC:  { name: 'Treasure DAO',   category: 'gaming' },
  YGG:    { name: 'Yield Guild Games', category: 'gaming' },
  PIXEL:  { name: 'Pixels',         category: 'gaming' },
  RONIN:  { name: 'Ronin',          category: 'gaming' },
  BEAMX:  { name: 'Beam',           category: 'gaming' },
  XAI:    { name: 'Xai Games',      category: 'gaming' },
  BIGTIME:{ name: 'Big Time',       category: 'gaming' },
  ALICE:  { name: 'My Neighbor Alice', category: 'gaming' },
  TLM:    { name: 'Alien Worlds',   category: 'gaming' },
  AGLD:   { name: 'Adventure Gold', category: 'gaming' },
  GMT:    { name: 'STEPN',          category: 'gaming' },
  SLP:    { name: 'Smooth Love Potion', category: 'gaming' },
  NOT:    { name: 'Notcoin',        category: 'gaming' },
  DOGS:   { name: 'Dogs',           category: 'gaming' },
  HMSTR:  { name: 'Hamster Kombat', category: 'gaming' },
  CATI:   { name: 'Catizen',        category: 'gaming' },
  PORTAL: { name: 'Portal Gaming',  category: 'gaming' },
  APE:    { name: 'ApeCoin',        category: 'gaming' },
  ENJ:    { name: 'Enjin',          category: 'gaming' },
  WIN:    { name: 'WINk',           category: 'gaming' },
  WAXP:   { name: 'WAX',            category: 'gaming' },
  FLOW:   { name: 'Flow',           category: 'gaming' },
  SOMI:   { name: 'Somnia',         category: 'gaming' },
  MANA:   { name: 'Decentraland',   category: 'gaming' },
  ANIME:  { name: 'Anime',          category: 'gaming' },
  ACE:    { name: 'Fusionist',      category: 'gaming' }, // tentative
  SUPER:  { name: 'SuperVerse',     category: 'gaming' },
  GUN:    { name: 'GUNZ',           category: 'gaming' }, // tentative

  // Infrastructure / Oracle
  LINK:   { name: 'Chainlink',      category: 'infra' },
  FIL:    { name: 'Filecoin',       category: 'infra' },
  GRT:    { name: 'The Graph',      category: 'infra' },
  RUNE:   { name: 'THORChain',      category: 'infra' },
  QNT:    { name: 'Quant',          category: 'infra' },
  BAND:   { name: 'Band Protocol',  category: 'infra' },
  API3:   { name: 'API3',           category: 'infra' },
  DIA:    { name: 'DIA',            category: 'infra' },
  PYTH:   { name: 'Pyth Network',   category: 'infra' },
  FLUX:   { name: 'Flux',           category: 'infra' },
  ANKR:   { name: 'Ankr',           category: 'infra' },
  STORJ:  { name: 'Storj',          category: 'infra' },
  FIDA:   { name: 'Bonfida',        category: 'infra' },
  ENS:    { name: 'Ethereum Name Service', category: 'infra' },
  GLM:    { name: 'Golem',          category: 'infra' },
  ZRO:    { name: 'LayerZero',      category: 'infra' },
  AXL:    { name: 'Axelar',         category: 'infra' },
  CELR:   { name: 'Celer Network',  category: 'infra' },
  SYN:    { name: 'Synapse',        category: 'infra' },
  WCT:    { name: 'WalletConnect',  category: 'infra' },
  BICO:   { name: 'Biconomy',       category: 'infra' },
  SAGA:   { name: 'Saga',           category: 'infra' },
  TIA:    { name: 'Celestia',       category: 'infra' },
  EIGEN:  { name: 'EigenLayer',     category: 'infra' },
  SSV:    { name: 'SSV Network',    category: 'infra' },
  BABY:   { name: 'Babylon',        category: 'infra' },
  ZKC:    { name: 'Boundless',      category: 'infra' },
  ZKP:    { name: 'Polyhedra Network', category: 'infra' },
  PROVE:  { name: 'Succinct',       category: 'infra' },
  THETA:  { name: 'Theta Network',  category: 'infra' },
  TFUEL:  { name: 'Theta Fuel',     category: 'infra' },
  LPT:    { name: 'Livepeer',       category: 'infra' },
  TOWNS:  { name: 'Towns Protocol', category: 'infra' },
  RAD:    { name: 'Radworks',       category: 'infra' },
  SIGN:   { name: 'Sign Protocol',  category: 'infra' },
  ACH:    { name: 'Alchemy Pay',    category: 'infra' },
  DYM:    { name: 'Dymension',      category: 'infra' },
  ALT:    { name: 'AltLayer',       category: 'infra' },
  PARTI:  { name: 'Particle Network', category: 'infra' },
  RLC:    { name: 'iExec RLC',      category: 'infra' },
  GNO:    { name: 'Gnosis',         category: 'infra' },
  CYBER:  { name: 'CyberConnect',   category: 'infra' },
  TRB:    { name: 'Tellor',         category: 'infra' },
  ADX:    { name: 'AdEx Network',   category: 'infra' },
  CVC:    { name: 'Civic',          category: 'infra' },
  GTC:    { name: 'Gitcoin',        category: 'infra' },
  CTK:    { name: 'CertiK/Shentu',  category: 'infra' },
  SFP:    { name: 'SafePal',        category: 'infra' },
  TWT:    { name: 'Trust Wallet Token', category: 'infra' },
  BAT:    { name: 'Basic Attention Token', category: 'infra' },
  WAL:    { name: 'Walrus',         category: 'infra' },
  HOT:    { name: 'Holochain',      category: 'infra' },
  REQ:    { name: 'Request Network', category: 'infra' },
  PUNDIX: { name: 'Pundi X',        category: 'infra' },
  JASMY:  { name: 'Jasmy',          category: 'infra' }, // tentative
  RED:    { name: 'RedStone Oracles', category: 'infra' }, // tentative
  INIT:   { name: 'Initia',         category: 'infra' },
  ZAMA_PLACEHOLDER: { name: 'unused', category: 'infra' }, // placeholder removed below

  // Privacy
  ZEC:    { name: 'Zcash',          category: 'privacy' },
  DASH:   { name: 'Dash',           category: 'privacy' },
  ZEN:    { name: 'Horizen',        category: 'privacy' },
  XVG:    { name: 'Verge',          category: 'privacy' },
  SCRT:   { name: 'Secret Network', category: 'privacy' },
  ROSE:   { name: 'Oasis Network',  category: 'privacy' },
  DUSK:   { name: 'Dusk Network',   category: 'privacy' },
  NIGHT:  { name: 'Midnight',       category: 'privacy' },
  ZAMA:   { name: 'Zama',           category: 'privacy' },
  MASK:   { name: 'Mask Network',   category: 'privacy' },
  COTI:   { name: 'COTI',           category: 'privacy' },
  PHA:    { name: 'Phala Network',  category: 'privacy' },
  NIL:    { name: 'Nillion',        category: 'privacy' },
  ARPA:   { name: 'ARPA Network',   category: 'privacy' },

  // RWA / Real World Assets
  XAUT:   { name: 'Tether Gold',    category: 'rwa' },
  PAXG:   { name: 'Pax Gold',       category: 'rwa' },
  ONDO:   { name: 'Ondo Finance',   category: 'rwa' },
  MANTRA: { name: 'MANTRA',         category: 'rwa' },
  CFG:    { name: 'Centrifuge',     category: 'rwa' },
  USUAL:  { name: 'Usual',          category: 'rwa' },
  PLUME:  { name: 'Plume Network',  category: 'rwa' },
  POLYX:  { name: 'Polymesh',       category: 'rwa' },
  HUMA:   { name: 'Huma Finance',   category: 'rwa' },
  LUMIA:  { name: 'Lumia',          category: 'rwa' }, // tentative

  // Tokenized Stocks & ETFs (bStocks)
  MUB:    { name: 'Micron Technology (bStock)', category: 'stocks' },
  SNDKB:  { name: 'SanDisk (bStock)',      category: 'stocks' },
  CRCLB:  { name: 'Circle Internet Group (bStock)', category: 'stocks' },
  NVDAB:  { name: 'Nvidia (bStock)',       category: 'stocks' },
  TSLAB:  { name: 'Tesla (bStock)',        category: 'stocks' },
  SPCXB:  { name: 'SpaceX (bStock)',       category: 'stocks' },
  AAPLB:  { name: 'Apple (bStock)',        category: 'stocks' },
  AMZNB:  { name: 'Amazon (bStock)',       category: 'stocks' },
  GOOGLB: { name: 'Alphabet (bStock)',     category: 'stocks' },
  MSTRB:  { name: 'Strategy (bStock)',     category: 'stocks' },
  BABAB:  { name: 'Alibaba (bStock)',      category: 'stocks' },
  NFLXB:  { name: 'Netflix (bStock)',      category: 'stocks' },
  IBMB:   { name: 'IBM (bStock)',          category: 'stocks' },
  INTCB:  { name: 'Intel (bStock)',        category: 'stocks' },
  AMDB:   { name: 'AMD (bStock)',          category: 'stocks' },
  QCOMB:  { name: 'Qualcomm (bStock)',     category: 'stocks' },
  PYPLB:  { name: 'PayPal (bStock)',       category: 'stocks' },
  ORCLB:  { name: 'Oracle (bStock)',       category: 'stocks' },
  ASMLB:  { name: 'ASML (bStock)',         category: 'stocks' },
  PLTRB:  { name: 'Palantir (bStock)',     category: 'stocks' },
  CRWVB:  { name: 'CoreWeave (bStock)',    category: 'stocks' },
  DELLB:  { name: 'Dell (bStock)',         category: 'stocks' },
  NOKB:   { name: 'Nokia (bStock)',        category: 'stocks' },
  GMEB:   { name: 'GameStop (bStock)',     category: 'stocks' },
  HOODB:  { name: 'Robinhood (bStock)',    category: 'stocks' },
  COINB:  { name: 'Coinbase (bStock)',     category: 'stocks' },
  MRVLB:  { name: 'Marvell Technology (bStock)', category: 'stocks' },
  AVGOB:  { name: 'Broadcom (bStock)',     category: 'stocks' },
  AMATB:  { name: 'Applied Materials (bStock)', category: 'stocks' },
  TSMB:   { name: 'TSMC (bStock)',         category: 'stocks' },
  RKLBB:  { name: 'Rocket Lab (bStock)',   category: 'stocks' },
  ARMB:   { name: 'Arm Holdings (bStock)', category: 'stocks' },
  IRENB:  { name: 'IREN (bStock)',         category: 'stocks' },
  CRDOB:  { name: 'Credo Technology (bStock)', category: 'stocks' },
  ASTSB:  { name: 'AST SpaceMobile (bStock)', category: 'stocks' },
  NBISB:  { name: 'Nebius Group (bStock)', category: 'stocks' },
  COHRB:  { name: 'Coherent Corp (bStock)', category: 'stocks' },
  FLNCB:  { name: 'Fluence Energy (bStock)', category: 'stocks' },
  WDCB:   { name: 'Western Digital (bStock)', category: 'stocks' },
  GLWB:   { name: 'Corning (bStock)',      category: 'stocks' },
  SMHB:   { name: 'VanEck Semiconductor ETF (bStock)', category: 'stocks' },
  SPYB:   { name: 'SPDR S&P 500 ETF (bStock)', category: 'stocks' },
  QQQB:   { name: 'Invesco QQQ ETF (bStock)', category: 'stocks' },
  TQQQB:  { name: 'ProShares UltraPro QQQ (bStock)', category: 'stocks' },
  SOXLB:  { name: 'Direxion Semiconductor Bull 3x (bStock)', category: 'stocks' },
  SOXSB:  { name: 'Direxion Semiconductor Bear 3x (bStock)', category: 'stocks' },
  EWYB:   { name: 'iShares MSCI South Korea ETF (bStock)', category: 'stocks' },
  AAOIB:  { name: 'Applied Optoelectronics (bStock)', category: 'stocks' },
  BMNRB:  { name: 'BitMine Immersion (bStock)', category: 'stocks' },
  AXTIB:  { name: 'AXT Inc (bStock)',      category: 'stocks' },
  MSFTB:  { name: 'Microsoft (bStock)',    category: 'stocks' },
  METAB:  { name: 'Meta Platforms (bStock)', category: 'stocks' },
  SMCIB:  { name: 'Super Micro Computer (bStock)', category: 'stocks' },

  // Sports Fan Token
  PSG:    { name: 'Paris Saint-Germain Fan Token', category: 'fantoken' },
  JUV:    { name: 'Juventus Fan Token', category: 'fantoken' },
  ACM:    { name: 'AC Milan Fan Token', category: 'fantoken' },
  BAR:    { name: 'FC Barcelona Fan Token', category: 'fantoken' },
  CITY:   { name: 'Manchester City Fan Token', category: 'fantoken' },
  ASR:    { name: 'AS Roma Fan Token', category: 'fantoken' },
  ATM:    { name: 'Atletico Madrid Fan Token', category: 'fantoken' },
  PORTO:  { name: 'FC Porto Fan Token', category: 'fantoken' },
  LAZIO:  { name: 'SS Lazio Fan Token', category: 'fantoken' },
  SANTOS: { name: 'Santos FC Fan Token', category: 'fantoken' },
  ALPINE: { name: 'Alpine F1 Fan Token', category: 'fantoken' },
  CHZ:    { name: 'Chiliz',         category: 'infra' }, // the underlying fan-token chain itself, not a club token

  // Fiat Currency (Binance fiat quote pairs, not crypto)
  EUR:    { name: 'Euro',           category: 'fiat' },
  USD:    { name: 'US Dollar',      category: 'fiat' },
  TRY:    { name: 'Turkish Lira',   category: 'fiat' },
  ZAR:    { name: 'South African Rand', category: 'fiat' },
  UAH:    { name: 'Ukrainian Hryvnia', category: 'fiat' },
  BRL:    { name: 'Brazilian Real', category: 'fiat' },
  ARS:    { name: 'Argentine Peso', category: 'fiat' },
  JPY:    { name: 'Japanese Yen',   category: 'fiat' },
  MXN:    { name: 'Mexican Peso',   category: 'fiat' },
  COP:    { name: 'Colombian Peso', category: 'fiat' },
  IDR:    { name: 'Indonesian Rupiah', category: 'fiat' },
  KZT:    { name: 'Kazakhstani Tenge', category: 'fiat' },
  AED:    { name: 'UAE Dirham',     category: 'fiat' },
}

function categoryOf(symbol) {
  return COINS[symbol]?.category || null
}

function nameOf(symbol) {
  return COINS[symbol]?.name || symbol
}

module.exports = { CATEGORIES, COINS, categoryOf, nameOf }